name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
          
      - run: npm ci
      - run: npm test
